### ISSUE TITLE
[Bug] The binary file path has changed in the release artifact starting from 0.4.1

### ISSUE THREAD

**Issue by debajyoti-truefoundry** [awslabs/soci-snapshotter#1007]
### Description

![image](https://github.com/awslabs/soci-snapshotter/assets/97010181/8136e40a-f323-454f-9111-ae2ca9ce56aa)

Please check the screenshot attached above. Was this an intended change? 

Feel free to close the issue if this will be the binary path in the release tar file from now on.

### Describe the results you expected

The binary path is the same as 0.4.0.

### Host information

Not required.

**Comment by debajyoti-truefoundry** [comment]
@austinvazquez This issue may be relevant to you based on your changes [here](https://github.com/awslabs/soci-snapshotter/pull/1005).

**Comment by Kern--** [comment]
Reopening to track that we still need to update the release artifacts

**Comment by austinvazquez** [comment]
Thanks for reporting the issue. Just returning back from holiday and will look into this more.

**Comment by austinvazquez** [comment]
Update on this issue. It looks like #1009 will resolve the issue for future releases. For the v0.4.1 release, I have put together a change management form to regenerate and rerelease the artifacts with the issue resolved. ECD is 1/4.

**Comment by austinvazquez** [comment]
@debajyoti-truefoundry , the artifacts for v0.4.1 release have been updated with the pathing fix. Thanks for reporting the issue!
