### ISSUE TITLE
Improve `check-flatc` rule and its invocation

### ISSUE THREAD

**Issue by wmesard** [awslabs/soci-snapshotter#101]
**Is your feature request related to a problem? Please describe.**

As discussed in PR #96 , the `check-flatc` rule in the Makefile could use some fixing. Also, it should be invoked by the build workflow.

**Describe the solution you'd like**
1. It is surprising (and I would argue, fundamentally broken) for a `check-*` rule to depend on another rule (`flatc`) that modifies the workspace. It should stop doing that.
1. `flatc` does not have a `--dryrun` option. So to detect if the generated files need to be updated, `check-flatc` could run it with `-o /tmp/$$` and then compare the resulting files to the existing files, and error out if they differ.
1. `check-flatc` is not being invoked in CI today. Workflows should invoke `make check` instead individual `check-*` rules, to fix this problem and prevent it from occurring for future `check-*` rules.

**Additional context**

See discussion in #96.

**Comment by rdpsin** [comment]
Closing since #102 and #104  have been merged.
