### ISSUE TITLE
Enable dependabot for the repo

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#118]
**Is your feature request related to a problem? Please describe.**
We need to be able to automatically update dependencies in snapshotter.

**Describe the solution you'd like**
Enable dependabot.

**Describe alternatives you've considered**

**Additional context**

**Comment by vkuzniet** [comment]
PR: https://github.com/awslabs/soci-snapshotter/pull/136

**Comment by torredil** [comment]
Can be closed now that #136 has been merged.
