### ISSUE TITLE
go-fuse: set AttrTimeout, EntryTimeout and NegativeTimeout to 600s

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#119]
**Is your feature request related to a problem? Please describe.**
The fuse process is not tuned. To achieve better performance for metadata operations, one can try tuning the following parameters: AttrTimeout, EntryTimeout and NegativeTimeout.

**Describe the solution you'd like**
User can set the above parameters in `config.toml`. The default values for those should be set to 600s.
The PR should contain the comparison for the workloads performance with the value 600s to baseline performance (all values are set to 0).

**Comment by rdpsin** [comment]
Where's the default value of 600s coming from?

**Comment by wmesard** [comment]
https://github.com/awslabs/soci-snapshotter/blob/5a80cdafeb08957b7a3296183fe4b00bb5929522/fs/fs.go#L134-L147

**Comment by vkuzniet** [comment]
Overall, trying to tune FUSE kernel cache expiration timeouts didn’t make any gains in improving RabbitMQ-type workloads. To make a difference with RabbitMQ specifically, it is suggested to set min-layer-size parameter to 10MiB when building the soci index. For more details, see the attached doc:
[Experimenting with FUSE kernel cache expiration timeouts.pdf](https://github.com/awslabs/soci-snapshotter/files/10058134/Experimenting.with.FUSE.kernel.cache.expiration.timeouts.pdf)
