### ISSUE TITLE
[FEATURE] soci index builder as a library

### ISSUE THREAD

**Issue by dvnguyen-amzn** [awslabs/soci-snapshotter#128]
**Is your feature request related to a problem? Please describe.**
Currently the index builder code is tightly coupled with Containerd. This blocks us on using the index builder module in environments without having containerd daemon running.

**Describe the solution you'd like**
We hope to move the index builder code into a separate module and the module should work without requiring on the present of the Containerd daemon. The new index builder module then can be imported by the soci-cli or other projects.

**Describe alternatives you've considered**
We need to have Containerd daemon running if we want to build soci index files.

**Comment by Kern--** [comment]
This is complete.
