### ISSUE TITLE
Look into other go-fuse tuning options

### ISSUE THREAD

**Issue by wmesard** [awslabs/soci-snapshotter#173]
**Is your feature request related to a problem? Please describe.**

#119 talks about finding better values for the FUSE tuning options we already have at our fingertips.
As a follow-on to that work, we should look at some of the other tuning options that go-fuse exposes
and see if we want to (a) use different defaults; (b) expose them as  _snapshotterConfig_ options for 
SOCI administrators to set.

**Additional context**
* https://github.com/hanwen/go-fuse/blob/4c25c9c1eecefb8beeea3daddf3486eb1dd48b89/fs/api.go#L566
* https://github.com/hanwen/go-fuse/blob/4c25c9c1eecefb8beeea3daddf3486eb1dd48b89/fuse/api.go#L145

**Comment by vkuzniet** [comment]
The conclusion is that the default parameters for go-fuse appear to be the sweet spot for running the metadata-heavy workloads like RabbitMQ. For more details, see the below doc:
[FUSE parameters tuning for RabbitMQ.pdf](https://github.com/awslabs/soci-snapshotter/files/10058172/FUSE.parameters.tuning.for.RabbitMQ.pdf)
