### ISSUE TITLE
Add more production-like integration tests

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#175]
**Is your feature request related to a problem? Please describe.**
The current set of integration tests verify that the basic lazy loading features offered by the SOCI snapshotter are working. There are, however, some gaps between the tests and they way the snapshotter will be used in a production system. It would be helpful to bridge some of those gaps to give us confidence that the current state as well as the state of each PR is production ready.

**Describe the solution you'd like**
- [x] A set of integration test that tests running multiple lazy-loaded containers simultaneously (with various compositions, e.g. 5 of the same container, 5 different containers, etc)
- [ ] An integration test that verifies that mounts are cleaned up appropriately - we can launch a container with `--rm` and verify that there are no FUSE mounts after the container exits.
- [x] An integration test that verifies that 2 of the same container running simultaneously can't write to each other

**Describe alternatives you've considered**
There is room for additional refactoring and unit tests to give us confidence in production readiness. More at metrics and logs to improve debuggability of the snapshotter would help as well.

**Additional context**
N/A

**Comment by vkuzniet** [comment]
The scope of this ticket is to implement the aforementioned tests and write any follow up tickets to address any failures encountered.
