### ISSUE TITLE
Split soci into 3 packages: soci, ztoc and compression

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#220]
**Is your feature request related to a problem? Please describe.**
To separate different concepts package `soci` needs to be split into 3 packages:
- soci
- ztoc
- compression 

**Describe the solution you'd like**
Create respective folders and split soci package into those 3.

**Describe alternatives you've considered**
See #103 for the reference on design doc.

**Additional context**
N/A

**Comment by kzys** [comment]
Closed?

**Comment by vkuzniet** [comment]
Yes. Closing it.
