### ISSUE TITLE
Create metrics to quantify the performance of background fetch operations

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#237]
**Is your feature request related to a problem? Please describe.**
The background fetch was dramatically redesigned. Old set of metrics became obsolete. 
We need to think if we need any metrics related to background fetch and if the answer is yes, they need to be implemented.

**Describe the solution you'd like**
1. One-pager on whether background fetch related metrics are needed for successful operations of soci snapshotter (including the precise definition of metrics is any).
2. Implement the aforementioned metrics.

**Comment by rdpsin** [comment]
Initially, we will add these 4 metrics:

- Number of spans fetched by bg-fetcher
- Number of errors during span fetch by bg-fetcher
- Time to complete background fetch for a single layer (Maybe some kind of histogram?)
- Periodically emit metrics for number of items in the work queue: `len(workQueue)`
