### ISSUE TITLE
Allow benchmarking framework to work with local registry

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#239]
**Is your feature request related to a problem? Please describe.**
Right now, the benchmarking framework is very ECR dependent. This needs to change, so it is possible to incorporate the benchmarks into the CI and also to allow to run experiments with other registries.

**Describe the solution you'd like**
1. Add option for benchmarks to not go with ECR auth for registries other than ECR (we can have local registries as a use case).
2. Add option to set plain-http=true for the registries, which do not return https header, e.g. local registries, such as (but not limited to) `ghcr.io/oci-playground/registry:v3.0.0-alpha.1`.

**Comment by Kern--** [comment]
After some additional thought, it's not clear that this would provide enough benefit to do right now. The benchmarking framework doesn't require ECR auth, it only requires a set of images to benchmark and whatever auth is needed for those images. A better solution is probably to get a set of soci-fied images into a public registry for CI and independent verification.
