### ISSUE TITLE
De-duplicate integration test code

### ISSUE THREAD

**Issue by rdpsin** [awslabs/soci-snapshotter#247]
**Is your feature request related to a problem? Please describe.**
There is quite a bit of code duplication going on in the integration and unit tests. 

Some examples:

-  [ ] dedup `genRandomByteData`
```
% ag -Q "func genRandomByteData" .
ztoc/ztoc_test.go
624:func genRandomByteData(size int) []byte {

fs/span-manager/span_manager_test.go
344:func genRandomByteData(size compression.Offset) []byte {

fs/backgroundfetcher/resolver_test.go
82:func genRandomByteData(size int64) []byte {

```

- [ ] `optimizeImage` and `optimizeImageWithOpts` functions in the integration tests.
- [x] identical snapshotter configs are defined separately in every single integration test. (#294)

We should de-duplicate all this code.

**Comment by djdongjin** [comment]
Meanwhile, probably we should also move those reusable helper functions to a common place such as `testutil.go` or something, instead of creating a helper function in `integration/aaa_test.go` and reusing in `integration/bbb_test.go`.
