### ISSUE TITLE
[BUG] `soci index rm` doesn't really delete the index data in storage

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#251]
**Describe the bug**

After `soci index rm indexDigest`, `soci index ls` doesn't show the index, but `soci index info` can still get the index.

**Steps To Reproduce**
```bash
$ sudo soci index list
DIGEST                                                                     SIZE    IMAGE REF                          PLATFORM       CREATED
sha256:1f223fc2899404ec0e4ce34f0ea0b975f3355c9232d2d6ff0f05978b3d094db1    1083    docker.io/library/nginx:latest     linux/arm64    n/a
sha256:b21cba14e88c476d703f6ec6a99d75bbba40cb6193e292da007b90014fcd9218    369     docker.io/library/alpine:latest    linux/amd64    n/a
sha256:c066d1313c553f44765af6104338ae62ecb0cd5f804f09b6541a887497a24d34    730     docker.io/library/alpine:latest    linux/amd64    n/a

$ sudo soci index rm sha256:1f223fc2899404ec0e4ce34f0ea0b975f3355c9232d2d6ff0f05978b3d094db1

$ sudo soci index list
DIGEST                                                                     SIZE    IMAGE REF                          PLATFORM       CREATED
sha256:b21cba14e88c476d703f6ec6a99d75bbba40cb6193e292da007b90014fcd9218    369     docker.io/library/alpine:latest    linux/amd64    n/a
sha256:c066d1313c553f44765af6104338ae62ecb0cd5f804f09b6541a887497a24d34    730     docker.io/library/alpine:latest    linux/amd64    n/a

$ sudo soci index info sha256:1f223fc2899404ec0e4ce34f0ea0b975f3355c9232d2d6ff0f05978b3d094db1
{"mediaType":"application/vnd.oci.artifact.manifest.v1+json","artifactType":"application/vnd.amazon.soci.index.v1+json","blobs":[{"mediaType":"application/octet-stream","digest":"sha256:dda6a58db05591ae0b3fcaef5ab49cacd73fbbcbfb53684ff848fa2242ce2cfb","size":1430704,"annotations":{"com.amazon.soci.image-layer-digest":"sha256:4b7f5b2a311310809ab89d92f6f71b0462722fe855d3b92c93098a528aa08791","com.amazon.soci.image-layer-mediaType":"application/vnd.oci.image.layer.v1.tar+gzip"}},{"mediaType":"application/octet-stream","digest":"sha256:57f308ff30c02e69c0419331f1f37b0b21e8e037c814aa564fb20ef145fd2880","size":718936,"annotations":{"com.amazon.soci.image-layer-digest":"sha256:3c419414ca9e1744a592d3379a913e0b03f596cba3cbb9e48e544931ac8e1d93","com.amazon.soci.image-layer-mediaType":"application/vnd.oci.image.layer.v1.tar+gzip"}}],"subject":{"mediaType":"application/vnd.docker.distribution.manifest.v2+json","digest":"sha256:4a68b1ef097839c7a2310b01a84ab464b78b227fac59bf26c5b1d074a5dba8d2","size":1570},"annotations":{"com.amazon.soci.build-tool-identifier":"AWS SOCI CLI v0.1"}}%
```

**Expected behavior**

After an index is removed, all its data should be deleted and `soci index info` shouldn't print the index info.

**Configuration (please complete the following information):**
 - OS: Amazon Linux 2
 - Snapshotter Version: main(2cf2a1607c016406946f79d01130dbfc304ed8e5)
 - Containerd Version: containerd github.com/containerd/containerd v1.7.0-beta.0-294-g36641eade 36641eade608deb2159ca4ac9973ea059f17570a

**Additional context**

**Comment by Kern--** [comment]
I think this can be merged with #252 and make the task to implement `soci index rm` properly. The initial implementation was a work around because we didn't have a way to guarantee that we pushed the most recently created index - it just deletes metadata to trick `soci push` into ignoring the old index. That's fixed by #246.

**Comment by djdongjin** [comment]
Close as merged into #252

**Comment by djdongjin** [comment]
> I think this can be merged with #252 and make the task to implement `soci index rm` properly. The initial implementation was a work around because we didn't have a way to guarantee that we pushed the most recently created index - it just deletes metadata to trick `soci push` into ignoring the old index. That's fixed by #246.

@Kern-- I reopened this issue and prefer keeping them (#251, #252) separately:

1. They are 2 different tasks with different reproduce steps/expected behaviors.
2. They should be resolved by different PRs.

Thanks.

**Comment by Kern--** [comment]
There are some open questions to answer here before implentation:
1) If we delete an index, do we also delete zTOCs that aren't referenced by another index?
2) Should we do all this deletion synchronously or with a garbage collector?
3) Can we integrate indices and zTOCs with containerd's content store to get containerd's garbage collection for free?

**Comment by djdongjin** [comment]
> There are some open questions to answer here before implentation:
> 
> 1. If we delete an index, do we also delete zTOCs that aren't referenced by another index?
> 2. Should we do all this deletion synchronously or with a garbage collector?
> 3. Can we integrate indices and zTOCs with containerd's content store to get containerd's garbage collection for free?

@Kern-- For 1 I think the answer should be yes, given we don't have a command like `soci ztoc rm`. If we don't delete zTOCs without index reference, they'll never be deleted (unless there is GC).

I think all the questions are related to if we can use containerd content store for zTOC/index storage, which is tracked in https://github.com/awslabs/soci-snapshotter/issues/423.

Also, the exact bug (`soci index info` can still see a index digest deleted by `soci index rm`) itself seems fixed:

```shell
$ ssoci index ls
DIGEST                                                                     SIZE    IMAGE REF    PLATFORM       MEDIA TYPE                                    CREATED
sha256:c49213575c1edfb320b1e35def5d4b8aea1bc78a474095f2e94c7b8ce9313d1e    1570                 linux/amd64    application/vnd.oci.image.manifest.v1+json    97h27m50s ago
sha256:32b32a0556c292d87aab2d65e5fd3398262186dc352aae640bab1ad4a02edea9    1570                 linux/amd64    application/vnd.oci.image.manifest.v1+json    237h25m12s ago
$ ssoci index rm sha256:c49213575c1edfb320b1e35def5d4b8aea1bc78a474095f2e94c7b8ce9313d1e
$ ssoci index info sha256:c49213575c1edfb320b1e35def5d4b8aea1bc78a474095f2e94c7b8ce9313d1e
soci: couldn't retrieve artifact for sha256:c49213575c1edfb320b1e35def5d4b8aea1bc78a474095f2e94c7b8ce9313d1e, not found
```

So I'll close this issue.
