### ISSUE TITLE
Improve integration tests for multiple container workloads by checking for overlayfs fallback

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#254]
Per https://github.com/awslabs/soci-snapshotter/pull/243#discussion_r1054961714, once we have a metric for overlays fallback occurrences, we should revisit the multiple container tests and have them also check to confirm that the containers are using soci, in addition to the current (pending merge) behavior of checking the functionality of the workload.

**Comment by Kern--** [comment]
Blocked on https://github.com/awslabs/soci-snapshotter/issues/190
