### ISSUE TITLE
soci ztoc info command should report some interesting metadata about the ztoc

### ISSUE THREAD

**Issue by wmesard** [awslabs/soci-snapshotter#255]
**Describe the solution you'd like**

Currently, `soci ztoc info` does little more than dump a list of files in the associated layer. There is some potentially interesting metadata about the zTOC itself that it could/should report. For example:
* the total size of the zTOC
* the sizes of the separate components (**zInfo** and **TOC**)
* number of spans
* min/max actual span size
* number of files
* number of files that cross multiple spans

**Comment by Kern--** [comment]
I think this is reasonable, but we should probably change `soci index info` to do something similar and create a new command (maybe `soci index inspect`) which outputs the full contents of the index (and ztoc for the equivalent comand).
