### ISSUE TITLE
[BUG] `soci ztoc info` products bespoke format

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#259]
**Describe the bug**
`soci ztoc info` produces a bespoke format of `key: value[, key:value ...]` that isn't consistent with other commands, such as `soci index info` which produces json

**Steps To Reproduce**
`soci ztoc info sha256:xxx`

**Expected behavior**
Some format equally readable by human and machine, probably JSON but an argument could be made for TOML or YAML. This issue does not suggest any changes to content, just the output format.

**Comment by Kern--** [comment]
https://github.com/awslabs/soci-snapshotter/issues/255 - we may rename this to `soci ztoc get`. Referencing that here in case that issue gets resolved before this one.

**Comment by sparr** [comment]
Resolved via #278
