### ISSUE TITLE
[FEATURE] Produce log output when container creation succeeds

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#271]
**Is your feature request related to a problem? Please describe.**
When containerd asks soci for a mount command, various failure modes will produce log output. However, success produces silence in the logs, making it hard to immediately tell whether containerd reached soci at all or fell back to a different snapshotter.

**Describe the solution you'd like**
One line of log output, probably at info level, declaring success.

**Describe alternatives you've considered**
Checking other logs and more directly monitoring activity while testing functionality for which success is uncertain.

**Comment by turan18** [comment]
@sparr Do you mean when a FUSE mount is successful (IE per layer)? Or the final mount call when a container is being created/run

**Comment by Kern--** [comment]
We already have logs that we're starting to work on a layer, unsuccessfully mounted as FUSE, and unsuccessfully mounted as overlay. I think it would make sense to add a per-layer log when either of those succeeds as well.

**Comment by turan18** [comment]
re: It seems that per-layer both local and remote snapshot success is logged already.
https://github.com/awslabs/soci-snapshotter/blob/main/snapshot/snapshot.go#L288
https://github.com/awslabs/soci-snapshotter/blob/main/snapshot/snapshot.go#L311

The current log-level is set to debug so we can potentially set it to info, as that is the default level we set.
