### ISSUE TITLE
Remove archived dependency on github.com/pkg/errors

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#321]
**Is your feature request related to a problem? Please describe.**

The dependency repo (https://github.com/pkg/errors) has been archived and the functionality it provides is implemented in builtin `errors` pkg.

**Describe the solution you'd like**

Remove this dependency and use builtin `errors` pkg directly.

https://github.com/search?q=repo%3Aawslabs%2Fsoci-snapshotter%20%22github.com%2Fpkg%2Ferrors%22&type=code

**Additional context**

Similar issue in containerd repo: https://github.com/containerd/containerd/issues/7940

Sample PR to remove the dependency: https://github.com/containerd/btrfs/pull/35

**Comment by Kern--** [comment]
Please take not of wherever we're using `errors.Is` following this change and double check that there is test coverage for that branching. If not, please file additional issues.
