### ISSUE TITLE
[BUG] [INTEG-TEST] prepareSociIndices returns incorrect ztocs for images

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#333]
**Describe the bug**
Images returned by `prepareSociIndices` do not have the correct ztocs as each images `ztocDigests` field is populated with the list of all ztocs rather the ztocs that only correspond to their layers. The `getZtocDigests()` just returns  the list of all generated ztocs.  
https://github.com/awslabs/soci-snapshotter/blob/235146bfc76f92a39a40e54b382fa88b1f9224cb/integration/index_test.go#L72-L97

**Expected behavior**

Either add a separate function named `getZtocDigestsForImage` or rename the current function. This function should only return a list of ztocs corresponding to a specific image. This should be resolved quickly once https://github.com/awslabs/soci-snapshotter/pull/314 is merged as you can simply query for a list of ztocs corresponding to an image by passing in the `--image-ref` parameter.

**Configuration (please complete the following information):**
 - OS: 
 - Snapshotter Version:
 - Containerd Version: 

**Additional context**

**Comment by djdongjin** [comment]
I think we should change `getZtocDigests` to get the index in `imageInfo` and then get ztocs from the index's blobs.

https://github.com/awslabs/soci-snapshotter/blob/235146bfc76f92a39a40e54b382fa88b1f9224cb/integration/index_test.go#L83-L97

**Comment by turan18** [comment]
> I think we can change `getZtocDigests` to get the soci index in `imageInfo` and then get ztocs from the index's blobs.
> 
> https://github.com/awslabs/soci-snapshotter/blob/235146bfc76f92a39a40e54b382fa88b1f9224cb/integration/index_test.go#L83-L97
> 
> Something like this:
> 
> https://github.com/awslabs/soci-snapshotter/blob/235146bfc76f92a39a40e54b382fa88b1f9224cb/integration/ztoc_test.go#L61-L71

Yea I think that'll work as well, I just though that the `--image-ref` solution would be a little cleaner, although I dont really mind either or

**Comment by djdongjin** [comment]
> Yea I think that'll work as well, I just though that the --image-ref solution would be a little cleaner, although I dont really mind either or

Yeah both work for me :)
