### ISSUE TITLE
Rename `CompressionInfo` to `Zinfo`

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#357]
**Is your feature request related to a problem? Please describe.**

We explain `ztoc` as two parts, `toc` and `zinfo` ([glossary](https://github.com/awslabs/soci-snapshotter/blob/main/docs/GLOSSARY.md)). However, [`Ztoc` struct](https://github.com/awslabs/soci-snapshotter/blob/1e87baff6ad9fec046c39e3ed7c4245b40efea79/ztoc/ztoc.go#L50) uses [`TOC`](https://github.com/awslabs/soci-snapshotter/blob/1e87baff6ad9fec046c39e3ed7c4245b40efea79/ztoc/ztoc.go#LL55C6-L55C6) for `toc`, but [`CompressionInfo`](https://github.com/awslabs/soci-snapshotter/blob/1e87baff6ad9fec046c39e3ed7c4245b40efea79/ztoc/ztoc.go#L56) for `zinfo`. It's confusing to developers and anyone read soci code.

**Describe the solution you'd like**

1. Rename [`CompressionInfo` struct](https://github.com/awslabs/soci-snapshotter/blob/1e87baff6ad9fec046c39e3ed7c4245b40efea79/ztoc/ztoc.go#L59) to `Zinfo`. (consistent with `Ztoc` format, e.g., upper-`Z` and lower-`t`).
2. Add comments to structs defined in [`ztoc.go`](https://github.com/awslabs/soci-snapshotter/blob/main/ztoc/ztoc.go).

**Describe alternatives you've considered**

Keep the `CompressionInfo` naming which is essentially `zinfo` in our docs/glossary.

**Additional context**

**Comment by sbuckfelder** [comment]
Can we check if we can do this in a backwards compatible way for flat buffers?
