### ISSUE TITLE
Integration test for network failure

### ISSUE THREAD

**Issue by rdpsin** [awslabs/soci-snapshotter#358]
**Is your feature request related to a problem? Please describe.**
The snapshotter uses retryable-http to retry requests if they fail. The config exposes certain fields to tune the snapshotter behavior in case of retries. 

https://github.com/awslabs/soci-snapshotter/blob/1e87baff6ad9fec046c39e3ed7c4245b40efea79/fs/config/config.go#L82-L84

We should have integration tests that verify the snapshotter behavior in case of network failures. 

**Describe the solution you'd like**
There are integration tests that verify snapshotter functionality in case of network failures. A simple way (?) to test it would be run the container in detach mode, use iptables to drop all outgoing connections, wait for some time, and reset iptables. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sparr** [comment]
Per planning meeting, an implementation here might look something like this:
* disable network connectivity
* trigger a request with retries configured for a short known duration
* trigger a request with retries configured for a longer known duration
* wait longer than the first duration but less than the second
* enable network connectivity
* confirm first request failed after exhausting retries
* confirm second request succeeded when connectivity was restored
