### ISSUE TITLE
[BUG] Eliminate "error" messages on successful rpull operations

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#361]
**Describe the bug**
A successful normal run of `soci image rpull` can produce log output that appear to be labeled as "error"s.

Examples:
* `{"error":"exec: \"fusermount\": executable file not found in $PATH","key":"default/3/extract-860035799-tI5g sha256:[...]","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/46/fs","msg":"fusermount not installed; trying direct mount","parent":"","time":"2023-01-25T20:45:24.972341422Z"}`
* `{"error":"skipping mounting layer sha256:[...] as FUSE mount: no ztoc for layer","key":"default/9/extract-93160834-sLdo sha256:[...]","level":"warning","msg":"failed to prepare remote snapshot","parent":"sha256:[...]","remote-snapshot-prepared":"false","time":"2023-01-25T20:45:25.097454762Z"}`

**Steps To Reproduce**
`soci image rpull [...]`

(comprehensive repro steps can be provided if necessary but would be unwieldy)

**Expected behavior**
"info" and "warning" level log output does not contain a field named "error"

**Comment by Kern--** [comment]
One option is to change the logrus error key to something like "context"

**Comment by Kern--** [comment]
We have decided that since this is idiomatic and there are better ways to solve this (e.g. using tooling to look at the log level), we will not implement this.
