### ISSUE TITLE
[BUG] SOCI requires go 1.19

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#367]
**Describe the bug**

https://github.com/awslabs/soci-snapshotter/pull/354 took a dependency on `atomic.Int32` which was [introduced in go 1.19](https://pkg.go.dev/sync/atomic#Int32).  

Go 1.18 is still supported and we should still be able to build for it.

**Steps To Reproduce**
 Build with go 1.18 or lower

**Expected behavior**
The project builds with go 1.18 or lower

**Configuration (please complete the following information):**
 - OS: 
 - Snapshotter Version:
 - Containerd Version: 

**Additional context**

**Comment by djdongjin** [comment]
maybe we should use minimum go version in our dockerfile so we'll know if we use features only in newer go version.

https://github.com/awslabs/soci-snapshotter/blob/b3a62fe0e8985cfc152bf867c8e287969b34a2e3/Dockerfile#L19
