### ISSUE TITLE
Create `.golangci.yml` to enable more linters

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#368]
**Is your feature request related to a problem? Please describe.**

Currently we don't have a `.golangci.yml` which means we only use the [enable by default](https://golangci-lint.run/usage/linters/#enabled-by-default) linters from golangci-lint. We should have more linters enabled.

**Describe the solution you'd like**

Create a `.golangci.yml` that enables more linters that are useful. Some reference: [containerd](https://github.com/containerd/containerd/blob/main/.golangci.yml), [nerdctl](https://github.com/containerd/nerdctl/blob/main/.golangci.yml), [stargz](https://github.com/containerd/stargz-snapshotter/blob/main/.golangci.yml), [cilium](https://github.com/cilium/cilium/blob/master/.golangci.yaml).

Meanwhile, related to this linter issue, we should remove `make check-lint` from our makefile and from [`github workflow`](https://github.com/awslabs/soci-snapshotter/blob/b3a62fe0e8985cfc152bf867c8e287969b34a2e3/.github/workflows/build.yml#L28) in favor of golangci action ([example](https://github.com/containerd/nerdctl/blob/b0701ba875880db5a6e7585df148f0eaea36283a/.github/workflows/test.yml#L42-L46)).

**Describe alternatives you've considered**

Continue to use the default linters.

**Additional context**

**Comment by djdongjin** [comment]
I think we should increase priority for https://github.com/awslabs/soci-snapshotter/issues/69, since it will increase our repo maintainbility by cleanning up makefile and moving some make rules to `hack/xxx_script.sh` or existing github action (e.g. golangci).

**Comment by rdpsin** [comment]
We already have one. https://github.com/awslabs/soci-snapshotter/blob/main/.golangci.yml

**Comment by djdongjin** [comment]
oops, somehow I missed this file 😂 . Will check if there are new linters we want to enable and close if not.

**Comment by djdongjin** [comment]
Close for now and will reopen if found new linters that might be useful.
