### ISSUE TITLE
[FEATURE] De-duplicate integration test setup code

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#372]
**Is your feature request related to a problem? Please describe.**
Many integration tests start with very similar setup code. See example in context below. This is somewhat a follow-up to #294.

**Describe the solution you'd like**
Deduplicate this code, probably into a few single-purpose helpers, possibly into a single test setup helper that takes some options.

**Describe alternatives you've considered**
Continue duplicating code in new tests.

**Additional context**
The below code is a common setup for a single test. Almost every line of it appears verbatim in 4 to 13 other tests, more with changed variable names, and will likely be duplicated into new tests:

	regConfig := newRegistryConfig()
	sh, done := newShellWithRegistry(t, regConfig)
	defer done()

	// Setup environment
	if err := testutil.WriteFileContents(sh, defaultContainerdConfigPath, getContainerdConfigYaml(t, false), 0600); err != nil {
		t.Fatalf("failed to write %v: %v", defaultContainerdConfigPath, err)
	}
	if err := testutil.WriteFileContents(sh, defaultSnapshotterConfigPath, getSnapshotterConfigYaml(t, false), 0600); err != nil {
		t.Fatalf("failed to write %v: %v", defaultSnapshotterConfigPath, err)
	}
	sh.
		X("update-ca-certificates").
		Retry(100, "nerdctl", "login", "-u", regConfig.user, "-p", regConfig.pass, regConfig.host)

	rebootContainerd(t, sh, "", "")

**Comment by Kern--** [comment]
An additional point that could help reduce this: `rebootContainerd`'s 3rd and 4th argument are custom containerd and snapshotter configs respectively. We might be able to remove the direct calls to `testutil.WriteFileContents` and use those fields instead.

https://github.com/awslabs/soci-snapshotter/blob/b3a62fe0e8985cfc152bf867c8e287969b34a2e3/integration/testutil.go#L530

**Comment by sparr** [comment]
@Kern-- How do you feel about taking advantage of that feature of `rebootContainerd` in places where the code currently uses the longer form once but `rebootContainerd` is called 3-5 times in subtests, so we'll be creating the files multiple times instead of once? I am leaning towards still making the change, for consistency and readability/comprehensibility.
