### ISSUE TITLE
[BUG] Min layer size config option integration test susceptible to future failure

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#373]
**Describe the bug**
The integration test for #343 will fail if the image used is updated, since it is not currently pinned.

**Steps To Reproduce**
Pin the rabbitmq image to an older version with different layer structure

**Expected behavior**
Test still functions as expected.

**Additional context**
Per @Kern-- in https://github.com/awslabs/soci-snapshotter/pull/343#discussion_r1091221204 a good approach here would be to check the sizes of the layers and choose a min layer size at the median layer size. This would ensure there are some skipped and some non-skipped layers, and allow us to calculate the expected number of fuse mounts. It would also have the nice side effect of testing the case where the min layer size is equal to a specific layer's size (which would fail if the code had a < vs <= mixup).

**Comment by Kern--** [comment]
I think we should still do the improvement in the additional context. We will probably eventually update which pinned version we're using.

**Comment by hanyuel** [comment]
+1 to using median layer size.
