### ISSUE TITLE
[BUG] Unused plugins produce error messages in logs on expected failure to load

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#377]
**Describe the bug**
Containerd feature plugins such as OpenTelemetry and CNI, as well as filesystem plugins like aufs and btrfs, will not load if modules are unavailable or configuration files are not present. This produces error messages, despite almost always not being an error condition. Some of these are at different log severity levels (info, warning, error).

**Steps To Reproduce**
`make integration`

**Expected behavior**
Avoid these errors, or at least logging them, when they are expected behavior.

**Additional context**
`make integration` produces 19 instances of each of the following:
* `{"error":"aufs is not supported (modprobe aufs failed: exec: \"modprobe\": executable file not found in $PATH \"\"): skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..."`
* `{"error":"cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config","level":"error","msg":"failed to load cni during init, please check CRI plugin status before setting up network for pods"`
* `{"error":"devmapper not configured","level":"warning","msg":"could not use snapshotter devmapper in metadata plugin"`
* `{"error":"devmapper not configured","level":"warning","msg":"failed to load plugin io.containerd.snapshotter.v1.devmapper"`
* `{"error":"no OpenTelemetry endpoint: skip plugin","level":"error","msg":"failed to initialize a tracing processor \"otlp\""`
* `{"error":"no OpenTelemetry endpoint: skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.tracing.processor.v1.otlp\"..."`
* `{"error":"path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs (tmpfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..."`
* `{"error":"path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..."`

and 43 instances of:
* `level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"`
* `level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"`
* `level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exec: \"modprobe\": executable file not found in $PATH \"\"): skip plugin" type=io.containerd.snapshotter.v1`
* `level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs (tmpfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1`
* `level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1`
* `level=info msg="skip loading plugin \"io.containerd.tracing.processor.v1.otlp\"..." error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1`
* `level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"`
* `level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"`

**Comment by Kern--** [comment]
These are containerd startup logs. We can see if there are existing containerd options that we should set to hide some of them, but most likely this will need to be opened upstream.
