### ISSUE TITLE
[FEATURE] Review dependencies for concerns

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#412]
**Is your feature request related to a problem? Please describe.**
We have direct dependencies on multiple packages with very low version numbers, including `0.0.0`, and with descriptions describing their experimental nature. This could be dangerous.

**Describe the solution you'd like**
Per meeting discussion, the ask here is to survey our dependencies and open new tasks for any that seem dangerous or in need of remediation.

**Additional context**
For indirect dependencies, we agreed we are comfortable relying on the trust of the direct dependency in question. If `containerd` is importing an experimental package, we can rely on them to vet it. If a much more niche direct dependency imports an experimental package, that deserves more attention.

**Comment by djdongjin** [comment]
Looking into our direct dependencies, I didn't notice any concerns.

Below is a summary and reason why I think not concerns. We can close this if no one found other potential concerns. @Kern-- @turan18 @sparr 

```shell
# from containerd, coreos, docker; stable
github.com/containerd/containerd v1.6.19
github.com/containerd/continuity v0.3.0
github.com/coreos/go-systemd/v22 v22.5.0
github.com/docker/cli v23.0.1+incompatible
# from docker, used by containerd https://github.com/containerd/containerd/blob/5da7e2c097952bce07ed5874355dedff72c9c343/go.mod#L29
github.com/docker/go-metrics v0.0.1
# from golang / google
github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
github.com/google/flatbuffers v22.12.6+incompatible
github.com/google/go-cmp v0.5.9
github.com/google/uuid v1.3.0

# popular fuse go pkg; stable
github.com/hanwen/go-fuse/v2 v2.2.0

# from hashi; being maintained
github.com/hashicorp/go-multierror v1.1.1
github.com/hashicorp/go-retryablehttp v0.7.2

# stable; popular zstd pkg
github.com/klauspost/compress v1.16.0

# from moby; containerd uses.
github.com/moby/sys/mountinfo v0.6.2

# stable; from trust source (golang, k8s, oci, prometheus, etc)

github.com/opencontainers/go-digest v1.0.0
github.com/opencontainers/image-spec v1.1.0-rc2
github.com/prometheus/client_golang v1.14.0
go.etcd.io/bbolt v1.3.7
golang.org/x/crypto v0.6.0
golang.org/x/sync v0.1.0
golang.org/x/sys v0.5.0
golang.org/x/time v0.3.0
google.golang.org/grpc v1.53.0
k8s.io/api v0.26.2
k8s.io/apimachinery v0.26.2
k8s.io/client-go v0.26.2
k8s.io/cri-api v0.25.7
oras.land/oras-go/v2 v2.0.0

# popular/being-maintained pkgs
github.com/montanaflynn/stats v0.7.0
github.com/pelletier/go-toml v1.9.5
github.com/urfave/cli v1.22.12
github.com/rs/xid v1.4.0
github.com/sirupsen/logrus v1.9.0
```

**Comment by sparr** [comment]
Agree. Thanks for the review.
