### ISSUE TITLE
Scrub Logs for Customer Information

### ISSUE THREAD

**Issue by sbuckfelder** [awslabs/soci-snapshotter#416]
As we intend soci-snapshotter to be used in cloud services we want to ensure that logs do not include any customer identifiable information such as filenames, image names, etc...

### What Needs To Be Done
1) Go through the identify when the code writes to the log (`grep -ri log *` ?) and ensure there is not any identifable info
2) Look through existing logs (maybe run the benchmarker?) and see if any identifiable info is present

**Comment by sparr** [comment]
After discussion of security concerns, I intend to ensure that all logging of file paths and contents within images is not enabled by default, and to update the comments and docs regarding more verbose logging to ensure the user knows that this could emit confidential/secret information. The summary in the previous comment will serve as guidance during a future security review.

**Comment by sparr** [comment]
Logging of file paths and contents from inside images does not happen at default log level, and the linked PR will update comments to explain this.
We are choosing not to audit deeper call stacks where errors from lower level functions might propagate sensitive information up to log output.

**Comment by sparr** [comment]
This issue is complete. Notes here will be used in a future audit of code and behavior for sensitive information concerns.
