### ISSUE TITLE
soci-snapshotter should optionally use the Referers API to discover the remote SOCI index

### ISSUE THREAD

**Issue by wmesard** [awslabs/soci-snapshotter#44]
**Is your feature request related to a problem? Please describe.**

Today, soci-snapshotter has to be [explicitly told](https://github.com/awslabs/soci-snapshotter/blob/aef69ad5ab220144efe9a66ffa78d0fc625fa6aa/docs/GETTING_STARTED.md#preparing-soci-snapshotter) the digest of the SOCI index that is associated with the image in the remote repository.

That's fine for some installations, where an outside agent will be doing that query anyway (via the Referrers API) to figure out which snapshotter to use. But for some installations--e.g., anyone running containerd themselves--forcing them to feed us the SOCI index digest (using `soci rpull`) is...um...stupid. [Referrers API](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) was developed specifically to relieve clients of this burden.

So let's fix it.

**Describe the solution you'd like**

The SOCI index digest should be optional in both the `client.Pull` call and the `soci rpull` command line. If it is not specified, then the snapshotter itself will use [Referrers API](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) to try to look it up.

If Referrers API returns more than one result, the snapshotter will use the first one in the list. (For now. We can iterate on this to later.)

**Describe alternatives you've considered**

If I were running the world, containerd would be allowed to have multiple snapshotters installed, and its snapshotter plugin interface have a new call which would happen before Prepare to do dynamic snapshotter selection. That is, containerd would ask each configured snapshotter "Hey, do you want to handle this image?" In that world, soci-snapshotter would do the Referrers API call at that time.

Alas, that is not the world in which we live. It could be. [containerd #6657](https://github.com/containerd/containerd/issues/6657) is trying to solve a similar problem.

**Additional context**

As part of this work, references to the `soci rpull` command will be removed from the *GETTING_STARTED.md* guide. In other words, the only thing you need to do on the runtime host, is launch the snapshotter, and then `ctr i run` the image. No `soci` CLI commands needed. That way, the demo is more wicked cool, and it is more obvious how SOCI can be used for production workloads.

If this fix is implemented after [soci-snapshotter #42](https://github.com/awslabs/soci-snapshotter/issues/42), then it would be fine if it only works for Reference Types and not ORAS. ORAS is going away, so there's no point in writing throwaway code.

**Comment by kzys** [comment]
https://www.docker.com/blog/extending-docker-integration-with-containerd/

> We’re replacing Docker’s graph drivers with containerd’s snapshotters.

So by making the digest optional, we could use SOCI snapshotter with Docker Engine.

**Comment by Kern--** [comment]
> As part of this work, references to the soci rpull command will be removed from the GETTING_STARTED.md guide. In other words, the only thing you need to do on the runtime host, is launch the snapshotter, and then ctr i run the image. No soci CLI commands needed. That way, the demo is more wicked cool, and it is more obvious how SOCI can be used for production workloads.

As great as this would be, we don't have all the pieces to do it yet. 

For each layer during a pull, containerd will go to the snapshotter first to check if there is already a snapshot for the "key" (which is opaque from the snapshotter's perspective). If not, it will call `Prepare` to setup a new mount point - this is the point at which we need to determine whether we're doing lazy loading or not. Unfortunately, by default `Prepare` only receives the key, and the parent snapshot's key. We don't have any information about the image or where to look for a SOCI index manifest. 

`rpull` gets around this by injecting additional labels into the `Prepare` call. Right now, that's the SOCI index digest, but could be the referrers API URL or even just image ref. 

So for now, we will need something other than `ctr i pull`. To do something fancier would require a discussion with containerd and probably a change in the Snapshotter API.

**Comment by Kern--** [comment]
Another thing worth noting is that if the client doesn't pass the SOCI index digest, then we will need to add some other unambiguous label to each layer to identify which SOCI index it should be pulled with (e.g. the image manifest digest).

The alternative is that we could leave the snapshotter as it is and have `source. AppendDefaultLabelsHandlerWrapper` make the referrers API call in the client.
