### ISSUE TITLE
[Bug] Clean up labels used by SOCI and switch to containerd's

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#458]
### Description

SOCI defines a list of labels it uses. However, these labels have the following issues:

1. Located in different places: [config.go](https://github.com/awslabs/soci-snapshotter/blob/aed937970e4b35dac5bf65fd38ad4bc6208c0ef6/fs/config/config.go#L42-L46), [remote.go](https://github.com/awslabs/soci-snapshotter/blob/56534c70965d326ed9963f9a0fa5f0ecba9d3bb9/fs/source/source.go#L79).
2. Labels that are not used at all or deprecated: [`config.TargetImageRefLabel`](https://github.com/awslabs/soci-snapshotter/blob/aed937970e4b35dac5bf65fd38ad4bc6208c0ef6/fs/config/config.go#L43)
3. Labels that mean the same thing but have different keys: [`SociIndexDigestLabel`](https://github.com/awslabs/soci-snapshotter/blob/aed937970e4b35dac5bf65fd38ad4bc6208c0ef6/fs/config/config.go#L46), [`SociIndexDigestLabel`](https://github.com/awslabs/soci-snapshotter/blob/aed937970e4b35dac5bf65fd38ad4bc6208c0ef6/fs/source/source.go#L108).
4. Labels we take from stargz but we didn't really use: [`targetUrls`](https://github.com/awslabs/soci-snapshotter/blob/aed937970e4b35dac5bf65fd38ad4bc6208c0ef6/fs/source/source.go#L97-L103); based on the discussion, this label is used for ipfs only: https://github.com/containerd/nerdctl/pull/2063#discussion_r1121746511

Another issue is that we probably should remove the mention of `com.amazon`? (I'm not sure about this)

https://github.com/awslabs/soci-snapshotter/blob/59b35d4817a4faa82f43bda27a81e4e0c3665daf/soci/soci_index.go#L49-L53

### Steps to reproduce the bug

See the code link above

### Describe the results you expected

1. Resolve the itemized issues.
2. Change to use containerd's label definition for remote snapshotter: https://github.com/containerd/containerd/blob/main/pkg/snapshotters/annotations.go

A similar effort for 2 for stargz can be found here: https://github.com/containerd/stargz-snapshotter/pull/1131

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by Kern--** [comment]
We can switch to containerd labels when creating SOCI indices, but we probably need to continue to accept the old labels in the snapshotter so that it doesn't break existing indices.

**Comment by turan18** [comment]
Changing our labels (to use containerd CRI labels) will require a change both within the soci cli (creating labels) as well as the snapshotter(consuming the labels). This is effectively a breaking change as users will have to update both the cli and the snapshotter. This change should be communicated in our v0.2 release as a breaking change.
