### ISSUE TITLE
[Bug] Test span access that are located at different places of a zinfo/layer

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#462]
### Description

When accessing a chunk of data/file/span in a layer via zinfo, we need to provide a range of the accessed data (e.g, buf[start:end]).

Previously we had code that, when constructing the range, decremented 1 on the end offset:

https://github.com/awslabs/soci-snapshotter/blob/00474ecf61cfb905a0d6436b516110050bb6435c/ztoc/ztoc.go#L127-L131

which is not right because for slice range access it's left-inclusive range. (see discussion https://github.com/awslabs/soci-snapshotter/pull/453#discussion_r1120742880).

### Steps to reproduce the bug

See above code snippet.

### Describe the results you expected

Have unit or integration test to validate data access via ztoc/zinfo for the follow scenarios:

1. Access data at the beginning of a layer (e.g. 1st span/file)
2. Access data in the middle of a layer (e.g., a random span/file)
3. Access data at the end of a layer (e.g., the last span/file)

Probably we can add more test to the `get-file` integration test. Or unittest for ztoc/zinfo if there is.

### Host information

Not related, not runtime bug, bug found in code.

**Comment by sondavidb** [comment]
Is this fixed by #397?
