### ISSUE TITLE
[FEATURE] `metadata/db` shouldn't be a sub-pkg of `metadata`

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#464]
### Description

While trying to fix #310. I notice `metadata/db` is a sub-pkg of `metadata`. However, it leads to a wired situation that the sub-pkg is importing the parent pkg, but the parent pkg doesn't import sub-pkg:

https://github.com/awslabs/soci-snapshotter/blob/00474ecf61cfb905a0d6436b516110050bb6435c/metadata/db/db.go#L41

https://github.com/awslabs/soci-snapshotter/blob/00474ecf61cfb905a0d6436b516110050bb6435c/metadata/db/reader.go#L51

https://github.com/awslabs/soci-snapshotter/blob/00474ecf61cfb905a0d6436b516110050bb6435c/metadata/metadata.go#L35-L42

This is exactly on the contrary of how we should define a sub-pkg: sub-pkg should be a standalone component. The parent pkg or others can import sub-pkg if it only uses that specific component.

Now with this structure, anyone importing the sub package is esentially import the sub and the whole parent package.

### Describe the solution you'd like

Combine them into a single `metadata` pkg.

A similar example is that [`soci/artifacts.go`](https://github.com/awslabs/soci-snapshotter/blob/main/soci/artifacts.go) is also the _db_ of soci indices, but it's not in a `db` subpackage.

### Describe any alternative solutions/features you've considered

Switch the parent and sub package (`metadata` and `metadata/db` -> `db` and `db/metadata`). This is not an optimal solution.

**Comment by sparr** [comment]
How much of metadata does metadata/db need? If it's significantly less than all of it, then a refactor to split that out could be in order.

**Comment by djdongjin** [comment]
This specific `metadata/db` is not a standalone component, it's the bolt db wrapper for `metadata`. Similarly we have [soci/artifacts.go](https://github.com/awslabs/soci-snapshotter/blob/main/soci/artifacts.go) for artifact db.

Right now since we only have this 2 blot db wrapper (for metadata and artifact), I think it okay to keep those wrapper in their own package (i.e. in `soci` or `metadata`, not a `xx/db` sub package).

If we really have more bolt db wrappers, we can move to a standalone `./db` package within which there is `db/metadata.go` and `db/artifacts.go`, etc. An example is containerd's [metadata](https://github.com/containerd/containerd/tree/main/metadata) package (corresponds to the `./db` here) that has bolt db wrappers for image/container/namespaces/etc.

**Comment by Kern--** [comment]
> However, it leads to a wired situation that the sub-pkg is importing the parent pkg, but the parent pkg doesn't import sub-pkg

I'm not sure this is such a weird situation. In the go standard library, [crypto](https://cs.opensource.google/go/go/+/master:/src/crypto/), [encoding](https://cs.opensource.google/go/go/+/master:/src/encoding/), and [hash](https://cs.opensource.google/go/go/+/master:/src/hash/) all follow this pattern where sub-package import the parent, but not the other way around. 

Stargz implements `metadata/memory` so I think the idea is to make things clear by having, e.g., `db.NewReader` vs `memory.NewReader`. I think we can make the argument that having that flexibility isn't valuable to us, but I don't think the package relationship is a convincing argument.

**Comment by djdongjin** [comment]
> but I don't think the package relationship is a convincing argument.

yeah I agree now that the "sub-package shouldn't import parent package" is not a convincing argument :) It makes sense sometimes that parent provides high-level abstractions (interface, data structure) and each sub-package provides a different impl.

Still feel #467 (combine them) has benefit now as this specific abstraction (1). is not necessary/valuable to us; (2). complicates our test code (each parent/sub pkg has a `testutil.go` to share test code; (3). inconsistent with other code ([`soci/artifacts.go`](https://github.com/awslabs/soci-snapshotter/blob/main/soci/artifacts.go), it might be a good/bad convention, but we should keep them consistent); (4). can be easily changed back if later we have a non-db impl of `metadata`.
