### ISSUE TITLE
[FEATURE] Abstract monitoring of log files for soci and containerd

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#520]
### Description

`testutil.RemoteSnapshotMonitor` and the incoming `testutil.FatalMonitor` implement scanning/monitoring of the soci log output for particular patterns. Before a third such behavior is implemented we should abstract this to a more generally usable form.

### Describe the solution you'd like

At minimum, a log monitor method that can be passed in a function to do the scanning (like `testutil.RemoteSnapshotMonitor.ScanLog` or `testutil.ScanFatalLog`).
Ideally, a single method implementing the outer loop logic shared by them, and a way to register the specific comparisons/checks unique to those functions, so a single log scanner can apply all of the necessary rules in one pass.

### Describe any alternative solutions/features you've considered

Continuing to reproduce the code in question would be faster in the short term but more fragile.

**Comment by Kern--** [comment]
We should also consider merging this with the benchmarker's log scanning. We might want a separate internal package for this.

**Comment by Kern--** [comment]
Our integration tests are currently flaky because our current log monitors are only getting some of the log lines when we run 2 at the same time. This issue would solve that.
