### ISSUE TITLE
[FEATURE] Add year to copyright notices

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#529]
### Description

Our boilerplate "Copyright The Soci Snapshotter Authors" does not include a year, which is suggested/required by the [official Apache license template](https://www.apache.org/licenses/LICENSE-2.0#apply), and I believe also important for legal reasons.

### Describe the solution you'd like

I propose updating every such file with the year the file was last modified, and adding a CI check to confirm that modifications to files in a new year update the copyright notice.

**Comment by Kern--** [comment]
The guidance we have received is that we do not need copyright year in our notices and that our current headers are sufficient.

**Comment by sparr** [comment]
I also note that they are not present in the stargz codebase from containerd. I will follow up on that guidance and close this issue.
