### ISSUE TITLE
[FEATURE] Quantify resource consumption of the snapshotter

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#552]
### Description

We need to quantify resource consumption of SOCI (e.g., memory, CPU), ideally compare this against OverlayFS

### Describe the solution you'd like

1) A set of scripts that can:
-  Quantify memory and CPU when Idle
- Quantify memory overhead compared to OverlayFS for running a workload

2) An analysis using those scripts including any parameters used so that we can have reproducible results.

### Describe any alternative solutions/features you've considered

Do nothing

**Comment by Kern--** [comment]
We should use the outcome of this to determine the relevance/priority of https://github.com/awslabs/soci-snapshotter/issues/113
