### ISSUE TITLE
[FEATURE] Skip indexing unknown compression types

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#591]
### Description

If the SOCI index builder encounters an unknown compression type it will fail the index build. We should skip unknown layers by default with a flag.

### Describe the solution you'd like
We should skip indexing unknown layer types and indicate why we skipped that layer like:

`ztoc skipped - unsupported compression: zstd`
`ztoc skipped - layer is smaller than min-layer-size: 1000000`

If the builder skips all ztocs, it should return an error

### Describe any alternative solutions/features you've considered

Alternatively, we could fail by default and require a flag to skip the layers. This would add the benefit that it's very explicit when lazy loading isn't going to work, but adds friction when onboarding. 

### Any additional context or information about the feature request

Similar to https://github.com/awslabs/soci-snapshotter/issues/580

**Comment by djdongjin** [comment]
How about making the behavior as default (skip layers with unknown compression/compression we don't support)? It has several benefits:

1. As we support more compression, more layers will be supported automatically without changing how users use soci/cli.
2. Support images with mixed types of layers (uncompressed, gzip, zstd): only gzip layers will be lazily loaded.

But I'm not sure if SOCI's fall back (to overlayfs) mechanism already works for other types of layers.

**Comment by Kern--** [comment]
Maybe we could do default with a warning? I'd be concerned about index build succeeding and then customers seeing no benefit because it skipped all the layers.

**Comment by djdongjin** [comment]
> Maybe we could do default with a warning? I'd be concerned about index build succeeding and then customers seeing no benefit because it skipped all the layers.

Yeah we should have a warning, and highlight that a `layer sha256:ec66df5c883fd24406c6ef53864970f628b51216e8e1f3f5981c439ed6e4ed41 -> ztoc skipped` output means no ztoc/no lazy loading.

Ideally we should deliver the message beforehands mentioning what we support. For example:

1. (currently) images only with gzip layers;
2. (with this behavior) images with different types of layer but only gzip layer will be lazily loaded;
3. (in the future, as we add more support) we support lazy loading gzip layers, tar layers, etc.

**Comment by Kern--** [comment]
I think it would also be worth highlighting why it was skipped:
`ztoc skipped - unsupported compression: zstd`
`ztoc skipped - layer is smaller than min-layer-size: 1000000`

**Comment by sparr** [comment]
I would say that skipping all layers is a failure condition, even if intentional skipping behaviors were configured.
