### ISSUE TITLE
[FEATURE] Use docker credentials in `soci image rpull`

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#599]
### Description

#572 requests support for docker credentials in `soci push`.

`soci image rpull` also takes credentials, but uses an entirely different mechanism to handle them (containerd's `Resolver` rather than direct cli context parsing).

### Describe the solution you'd like

Support docker config credentials for `soci image rpull` as well.

### Describe any alternative solutions/features you've considered

Consolidating the credential / helper / keystore behavior between `soci push`, `soci image rpull`, and all of the `soci-snapshotter-grpc` behaviors could be a worthwhile effort before we make too many more disparate implementations of similar functionality.

**Comment by Kern--** [comment]
`soci image rpull` was removed in #998
