### ISSUE TITLE
[FEATURE] Remove `ocispec.MediaTypeArtifactManifest` usage

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#606]
### Description

`ocispec.MediaTypeArtifactManifest` has been removed in [image-spec v1.1.0-rc3](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc3/specs-go/v1/mediatype.go). We should remove its usage in SOCI.

### Describe the solution you'd like

Completely remove all use of `ocispec.MediaTypeArtifactManifest`.

### Describe any alternative solutions/features you've considered

Add it back in SOCI and use that.

**Comment by sparr** [comment]
Is there a recommended alternative/replacement media type for our use case or any similar one?

Can we preserve backward compatibility with indexes created in the past with this media type without foregoing media type verification or adding this media type in the soci codebase?

**Comment by djdongjin** [comment]
> Is there a recommended alternative/replacement media type for our use case or any similar one?

I believe we already use the [recommended replacement](https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidelines-for-artifact-usage) as default which is `image manifest` mediatype + `artifactType` within it to specific the artifact type.

> Can we preserve backward compatibility with indexes created in the past...

I don't think there is any indexes created with artifact media type in production, since we have made the switch for a while. Even there is, I think our "backward compatibility" depends on if registries support it or not and the exact behavior, since this artifact media type is no longer part of the OCI spec (at least in the current 1.1.0 rc)

**Comment by Kern--** [comment]
I'm in favor of removing it entirely. The only production registry that ever supported it is Azure and SOCI only ever supported it without jumping through hoops if you built an early version from source.

Even if you did have existing indices, they're not portable and probably never worked outside of a test environment.
