### ISSUE TITLE
[FEATURE] Make HTTP timeouts configurable

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#608]
### Description

We currently set custom [HTTP timeouts](https://github.com/awslabs/soci-snapshotter/blob/main/util/http/retry.go#L33-L35). Instead of having hard coded timeouts we should find a way to be able to make them configurable using SOCIs config file. Something similar to the [blob config](https://github.com/awslabs/soci-snapshotter/blob/main/fs/config/config.go#L77-L79). 

### Describe the solution you'd like

A place in the `config.toml` to define HTTP timeouts eg: 

```toml

[timeouts]
  request_timeout=x
  dial_timeout=x
  response_header_timeout=x

``` 

### Describe any alternative solutions/features you've considered

Should we have an overarching config that covers timeouts and retries (having only 1 config instead of a separate blob config)? This would mean that the artifact fetcher and span fetcher share the timeout and retry policy. If so this may be blocked on #224.

**Comment by Kern--** [comment]
We should have a top level config for timeouts and retries.
That config should use the same names (where applicable) as the blob config so that in the future we can replace the blob config with an embedded top level config.
