### ISSUE TITLE
[Bug] Blob resolver extra roundtrips

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#655]
### Description

There is exactly one [remotes.Resolve](https://github.com/awslabs/soci-snapshotter/blob/main/fs/layer/layer.go#LL385C26-L385C27) operation per SOCI eligible layer in an image. `remote.Resolve` returns an instance of a `Blob` which stores an instance of an [httpFetcher](https://github.com/awslabs/soci-snapshotter/blob/main/fs/remote/resolver.go#L114) struct which contains the client used to fetch spans. It also contains a [url](https://github.com/awslabs/soci-snapshotter/blob/main/fs/remote/resolver.go#L238) field that is supposed to contain the "real"/redirected URL of the blob so the client does not have to make extra round-trip(s) to fetch the blob (**given that the registry uses a separate backend for storage like ECR**). Currently, this does not happen. What ends up happening is we make a full [Roundtrip](https://github.com/awslabs/soci-snapshotter/blob/main/fs/remote/resolver.go#L304) with a given client to the suggested URL, [**which by default follows up to 10 redirects**](https://pkg.go.dev/net/http#Get). If the request is successful we set the URL to be the [original URL](https://github.com/awslabs/soci-snapshotter/blob/main/fs/remote/resolver.go#L314). 

Although not directly harmful, we do end up incurring a performance hit (most likely in the order of milliseconds) every time we want to make requests to fetch a span (eg: when running the container or background fetching) since we have to make an additional roundtrip(s) to get the blob. **Note: as mentioned above this is only an issue for registries that have 1 or more storage backends**

### Describe the results you expected

We should set the URL to be that last `URL` that a request was sent to to get a 200 response. 
```go
res, err := tr.RoundTrip(req)
if err != nil {
     return "", fmt.Errorf("failed to request: %w", err)
}
if res.Status == 200 {
 url := res.Request.URL.String()
}else{
  ....
}
```

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by Kern--** [comment]
For reference, this used to work correctly until stargz added retryable requests:
https://github.com/containerd/stargz-snapshotter/commit/ce4fb004ae05f7e8420fcbe0c714428dc306fc45#diff-f170c75b92738ce5b1a2384c22a812a13f826d52c99d082f070a6cacca129861L62

The behavior of `http.DefaultTransport` is to do exactly one round trip, not following any redirects. The added retryable client in that PR hides an `http.Client` inside the `http.Transport` and that inner client does follow redirects.

Whatever solution we come up with here should be contributed back to stargz as well.

**Comment by turan18** [comment]
We should verify that the authorizer is still able to get credentials for any nested storage backends once the credentials expire.**

**Comment by Kern--** [comment]
One thing to note: If we cache the redirected URL, we should re-do the auth/redirect process from scratch if the credentials expire.
