### ISSUE TITLE
[Bug] zTOC ordering requirement not documented

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#658]
### Description

The list of zTOCs in an index manifest must be in a deterministic order so that the manifest will have the same digest each time it is generated. For consistency with existing manifests that order should be the same as the order of layers in the image from which the manifest was generated.

This requirement was encountered and noted during the implementation around this comment: https://github.com/awslabs/soci-snapshotter/blob/main/soci/soci_index.go#L316-L317

### Describe the results you expected

Requirement described and explained in documentation, not just code or comments.

### Host information

N/A

**Comment by Kern--** [comment]
This might be a part of the SOCI index technical doc listed here: https://github.com/awslabs/soci-snapshotter/issues/405

It might be worth keeping this open to see if there's a place to put it before we write that whole doc.

**Comment by Kern--** [comment]
Closed by #877
