### ISSUE TITLE
[FEATURE] Support sha512 digests in `soci rebuild-db`

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#662]
### Description

`soci rebuild-db` only scans for content in `blobs/sha256/`

### Describe the solution you'd like

scan in `blobs/sha512/` also

### Any additional context or information about the feature request

Support for SHA512 is optional in https://github.com/opencontainers/image-spec/blob/main/descriptor.md#registered-algorithms

**Comment by turan18** [comment]
I think we do that already - https://github.com/awslabs/soci-snapshotter/blob/main/cmd/soci/commands/rebuild_db.go#L47 , walks through the blobs directory entirely.

**Comment by sparr** [comment]
Sorry, I must have misread.
