### ISSUE TITLE
Move build-tool installation logic out of Makefile

### ISSUE THREAD

**Issue by wmesard** [awslabs/soci-snapshotter#69]
**Is your feature request related to a problem? Please describe.**

Today, the Makefile contains a growing number of rules for installing build-time dependencies. This is an antipattern that hurts maintainability and portability. Makefiles should contain the logic to build project artifacts, and that is it. Dependencies should be documented in *README.md* or *BUILDING.md* and/or managed by a *configure.sh* script.

**Comment by torredil** [comment]
2
