### ISSUE TITLE
[Bug] Integration tests don't work on non-x86

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#696]
### Description

Our integration tests fail on other architectures. Here are some things we need to do to:

- [x] Fix a bug in our Dockerfile where `TARGETARCH` is not honored since it is not scoped locally. This causes us to use only amd64 artifacts. - #695 
- [ ] Remove dependency on ghcr.io/oci-playground/registry:v3.0.0-alpha.1 since its only available for amd64 architectures. Since the notion of OCI Artifact Manifests have seemingly been rejected from the v1.1.0 Image Spec I don't think we need a v1.1.0 compliant registry at least until the v1.1.0 spec has been finalized. We can then remove any tests that use this image - https://github.com/awslabs/soci-snapshotter/blob/801acef5adc5f7976fa7b482e1b1f829e6ee6097/integration/push_test.go#L133 and then set the default registry to be registry:2 here https://github.com/awslabs/soci-snapshotter/blob/801acef5adc5f7976fa7b482e1b1f829e6ee6097/integration/util_test.go#L423
- [ ] We have 2 tests that specifically use an amd64 variant of rabbitmq- [TestPullWithAribtraryBlobInvalidZtocFormat()](https://github.com/awslabs/soci-snapshotter/blob/184d1715fe4985936018f8013dd81c54019ae4e4/integration/pull_test.go#L415) and [TestPushAlwaysMostRecentlyCreatedIndex()](https://github.com/awslabs/soci-snapshotter/blob/184d1715fe4985936018f8013dd81c54019ae4e4/integration/push_test.go#L84). We should change them to use tags that support multiple architectures. 

### Steps to reproduce the bug

Run the integration tests on non x86 arch.

### Describe the results you expected

Integration tests should work with different architectures.

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by sparr** [comment]
> We have 2 tests that specifically use an amd64 variant of rabbitmq- [...] We should change them to use tags that support multiple architectures.

Those tags should be historic and static, not versions that might see backports or other new pushes.

**Comment by Kern--** [comment]
For the second issue, I think we can just skip that test on ARM for now.

**Comment by sparr** [comment]
@Kern-- Just skipping the test that uses the 1.1 registry is not sufficient. The image and container in question are also used in `composeBuildTemplate` which is used in `TestMain`'s call to `setup()`. https://github.com/awslabs/soci-snapshotter/blob/bde429dbb4bc08c3b80920909df240b812a87c62/integration/main_test.go#L129 This can probably also be skipped on other arch, but is nontrivial.

Also the Dockerfile will need to be modified to not attempt to pull the image in question on the wrong arch.

I'd like to discuss re-estimating this.
