### ISSUE TITLE
[FEATURE] Make docs consistent re soci / soci-snapshotter / soci-snapshotter-grpc / SOCI

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#709]
### Description

We have docs referring to this project and different parts of the project by different names, which can be confusing to new users.

### Describe the solution you'd like

Standardize the terminology across docs and comments.

Proposal:
SOCI is the project
`soci` is the command line interface
soci-snapshotter is the snapshotter service when discussing it in a conceptual sense such as the gRPC API
`soci-snapshotter-grpc` is the service binary/process

**Comment by Kern--** [comment]
I agree that we should make it consistent.

I think the hardest distinction to make is the difference between soci-snapshotter (the conceptual component) and `soci-snapshotter-grpc` (the specific binary). I've been using "the SOCI snapshotter" for the former as a more succinct form of "the snapshotter from the SOCI project". I personally feel like this is more clear than "soci-snapshotter" but I'm curious what others think.

**Comment by sparr** [comment]
I am on board with that alternative as well.

**Comment by sparr** [comment]
I'm not sure I like the idea of a shorthand for the binaries. Those might deserve to either be enumerated or at least verbosely called out as "the SOCI snapshotter binaries"

**Comment by Kern--** [comment]
I agree with @sparr. We should try to be explicit to avoid confusion (there are already a lot of terms floating around).
