### ISSUE TITLE
[FEATURE] SOCI index documentation

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#757]
### Description

Create a new doc focused on the SOCI index including index/ztoc/toc/zinfo, and how they’re related to layers (and files in layers).
NOTE: don't forget to document that ztocs must be ordered the in the same order as the layers they reference. https://github.com/awslabs/soci-snapshotter/issues/658

### Any additional context or information about the feature request

Forked from #405

**Comment by turan18** [comment]
Closed by: #877
