### ISSUE TITLE
Set up permissions/controls on gh-pages branch

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#772]
The gh-pages branch was created with default configuration. It should be updated to require at least one reviewer, and possibly other constraints that make sense when implementing this or come up in discussion of this issue.

**Comment by Kern--** [comment]
The benchmark workflow automatically update github pages, we don't want to go through a pull request for that.

**Comment by sparr** [comment]
I believe that the workflow can be allowed to push directly to the branch independently of PRs requiring review. PR review would be for manually opened PRs that target the branch, such as the one used to create directories.

**Comment by Kern--** [comment]
Github doesn't allow you to require reviews on PRs unless you require PRs.
