### ISSUE TITLE
Remove libindexer

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#78]
**Is your feature request related to a problem? Please describe.**
soci snapshotter has indexer C component, which at the moment needs to be built separately into `libindexer.a` and then statically linked during snapshotter's compilation. This shouldn't be this way. 

**Describe the solution you'd like**
`gzip_indexer.go` and C files need to be located in the same directory. This will allow `cgo` to search for C files within the same directory where `gzip_index.go` is located and compile/link them on the fly without creating the additional artifact.

**Describe alternatives you've considered**

**Additional context**

**Comment by wmesard** [comment]
Benefit of doing this work: Eliminates a step in the build process. Simplifies the Makefile and the #cgo flags in gzip_index.go

**Comment by vkuzniet** [comment]
Already in main.
