### ISSUE TITLE
[Bug] Test against referrers API

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#808]
### Description

We recently had a change that removed our dependency on the GHCR registry in our integration tests since it was only supported on amd64 - #806. The GHCR registry provided support for the referrers API, allowing us to test pushing and pulling artifacts with it enabled - https://github.com/awslabs/soci-snapshotter/blob/ec1e62326578318ace5048c487b7e155a068dd4b/integration/push_test.go#L135 We should look into alternative registries that have support for multiple architectures and the referrers API, in the meantime. https://github.com/project-zot/zot seems to be a good candidate. Ideally, we'd like to be able to test against the fallback and the referrers API without having to build 2 separate registries. We should look into if its possible to disable the referrers API in Zot.

### Describe the results you expected

A test that pushes/pulls against a registry that supports the referrers API.

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by sondavidb** [comment]
Closed with #856
