### ISSUE TITLE
[FEATURE] Add documentation on how to get to clean state

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#818]
### Description

Currently, if the SOCI snapshotter is killed and restarted, it can end up in one of several broken states (e.g. due to invalid credentials, missing FUSE mounts, missing snapshots, etc). Just restarting the snapshotter usually immediately exits with errors. There should be documentation to explain how to get SOCI back into a good state and understanding what the bad state even is.

### Describe the solution you'd like

We should update either the getting started guide or the debugging guide with information about those errors, how to fix them gracefully (with `allow_invalid_snapshots` + removing the snapshots in containerd), and how to fix them forcefully (blowing away `/var/lib/containered` and `/var/lib/soci-snapshotter-grpc` and restarting containerd).

**Comment by sondavidb** [comment]
Fixed by #835.
