### ISSUE TITLE
[FEATURE] Support disabling file header verification

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#819]
### Description

https://github.com/awslabs/soci-snapshotter/pull/813 validates that a file's attributes match the tar header in the layer file on first read. Doing this requires downloading the tar header before downloading the data for the first read. In the case of reading from the beginning of the file, the two downloads likely use the same span and therefore the additional tar validation is cheap. However, there might be cases where files are not read from the beginning and the additional tar header fetch causes non-trivial latency.

For these cases, there should be an option to disable tar header verification for users that want maximum performance.

### Describe the solution you'd like

Ideally the existing [`disable_verification`](https://github.com/awslabs/soci-snapshotter/blob/7cc04aff01bce06f3b1759cf1eecf4cebdeeb2cb/config/fs.go#L51) bool would be plumbed through for this. 

Currently this is used to skip TOC verification (which is implemented as a no-op in SOCI) and is always set to true. These are remnants from code that was inherited from the stargz-snapshotter. We could repurpose it for this verificaiton.

### Describe any alternative solutions/features you've considered

We could add a new flag like `disable_file_verification`, but this would likely be confusing considering the more general option.

**Comment by sondavidb** [comment]
Fixed by #849
