### ISSUE TITLE
[FEATURE] Stop using `ctr` code in CLI

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#841]
### Description

The SOCI CLI is built using flags and helper methods directly from [`ctr`](https://github.com/containerd/containerd/tree/main/cmd/ctr). Often this ends up pulling in many flags that aren't needed or used which leaves the user guessing as to which ones are actually connected ([See this discussion for an example](https://github.com/awslabs/soci-snapshotter/discussions/839)).

For one example, `soci push` has the following flags which are not connected to anything:

```
   --skip-verify, -k               Skip SSL certificate validation
   --refresh value                 Refresh token for authorization server
   --hosts-dir value               Custom hosts configuration directory
   --tlscacert value               Path to TLS root CA
   --tlscert value                 Path to TLS client certificate
   --tlskey value                  Path to TLS client key
   --http-dump                     Dump all HTTP request/responses when interacting with container registry
   --http-trace                    Enable HTTP tracing for registry interactions
   --label value                   Labels to attach to the image
   --snapshotter value             Snapshotter name. Empty value stands for the default value. [$CONTAINERD_SNAPSHOTTER]  
   --max-concurrent-uploads value  Max concurrent uploads. Default is 10 (default: 10)
```

`ctr` is meant to be a debugging tool for containerd which means that it makes [no guarantees about stability](https://github.com/containerd/containerd/blob/main/RELEASES.md#public-api-stability). 

### Describe the solution you'd like

We should remove the direct references to CTR code and copy the flags that we use into our codebase.

We shouldn't bring over flags that aren't currently connected, but we should create issues for flags that would be useful to implement. We shouldn't confine ourselves to the specific flag names, but instead address the features the flags add.

**Comment by sondavidb** [comment]
Fixed with #998
