### ISSUE TITLE
[Bug] Replace `soci create/push` with `nerdctl push` in our documentation

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#844]
### Description

[`nerdctl` v1.6.0 ](https://github.com/containerd/nerdctl/releases/tag/v1.6.0) adds support for creating and pushing SOCI indexes. We should replace mentions of `soci create/push` with `nerdctl push` in our documentation. Note: The `nerdctl` CLI just shells out to the `soci` CLI, so we should mention that the `soci` CLI still needs to be installed. 

### Describe the results you expected

Replacing references of `soci create/push` with `nerdctl push`.

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by ningziwen** [comment]
Should we add as one option instead of replacing, as nerdctl is not a must-have to use soci. (Containerd is a must-have though).

**Comment by Kern--** [comment]
We need some way to manage container images in containerd. Right now, our alternative is `ctr`. While `nerdctl` is technically optional, the alternative (`ctr`) is pretty inappropriate for production use-cases.

If we eventually have a containerd-less option (or docker containerd support is default), then we can probably have options, but I think making nerdctl + SOCI CLI the only recommendation in our docs is reasonable.
