### ISSUE TITLE
Upgrade `go-fuse` to tagged revision 

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#855]
### Description

#852 upgraded `go-fuse` to commit [fc2c4d3](https://github.com/hanwen/go-fuse/commit/fc2c4d3da0a07dd49fa7c826f406c8e9c2842f32), as it contained a fix for a bug that would cause `cp/mv/install` to hang on sparse files. This issue tracks upgrading `go-fuse` to a tagged revision once the fix is included in a release.

### Describe the results you expected

Upgrade `go-fuse` to a tagged revision once the fix is included in a release.

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by bgardner-noggin** [comment]
Is it possible that we could get this released? eg release 0.4.1 containing this fix? This is blocking our ability to use SOCI indexes on ECS

**Comment by turan18** [comment]
Hey, sorry for the wait, we had some issues with updating our release process but they are resolved now. Release `v0.4.1` is now out, so if you are consuming SOCI via ECS on EC2 you can now pull this release in. If you are using Fargate this should already be available to you. Thank you for your patience!
