### ISSUE TITLE
[Bug] Memory aliasing keeps entire ztoc file in memory

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#967]
### Description

When looking at a heap profile of the soci snapshotter while a workload is running, the memory usage is dominated by `io.ReadAll` coming from `ztoc.Unmarshal`. The memory from `io.ReadAll` is the memory allocated to the ztoc when we read it from disk [here](https://github.com/awslabs/soci-snapshotter/blob/21ec5445ea5e0908861e60e92cbdcd70d3251c93/ztoc/ztoc_marshaler.go#L57). Normally, this buffer would be GC'd once the method returns, but `flatbufToZtoc` creates a `*Ztoc` which has a [direct reference to `compressionInfo.CheckpointBytes()`](https://github.com/awslabs/soci-snapshotter/blob/main/ztoc/ztoc_marshaler.go#L100) which forces the entire unparsed ztoc to remain in memory until that reference is released. Since the ztoc stays in memory for the lifetime of the container, the memory is used indefinitely.

I haven't looked too closely, so there might be other aliasing, but at the very least we should copy the checkpoint bytes so we can free the rest of the unparsed ztoc.

Example flamegraph (the image doesn't really matter, it seems to always be ztocs that use the memory):
<img width="1399" alt="heapprofile" src="https://github.com/awslabs/soci-snapshotter/assets/2304727/a0bec627-9233-47b6-8c55-3122e38ccd15">

### Steps to reproduce the bug

1) Launch a container with SOCI where the config contains `debug_address = ":6060"`
2) Wait for the ztocs to be downloaded and the fuse filesystems to be set up
3) curl for a heap profile: `curl -s localhost:6060/debug/pprof/heap > heap.pprof`
4) visualize the pprof: `go tool pprof -http :8080 ./heap.pprof`

### Describe the results you expected

`io.ReadAll` should not be present in the heap profile.

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by sondavidb** [comment]
Fixed in #975
