### ISSUE TITLE
check-flatc has to verify if flatbuf generated files have been modified

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#97]
**Describe the bug**
`check-flatc` does not identify that flatbuf generated files have been modified without using `flatc`.

**Steps To Reproduce**
1. Modify any of the files under `ztoc/fbs`
2. Run `make check-flatc`
3. Observe nothing happens

**Expected behavior**
1. `make check-flatc` needs to provide the difference between the contents in `ztoc/fbs` and a newly generated fbs files.

**Configuration (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by rdpsin** [comment]
Fixed in PR #102.
